version: '3'

services:
  db: 
    image: postgres:14-alpine
    container_name: blog_api_db
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blog_api

networks:
  bookmark:
    driver: bridge
